//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYPCenterManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Student Name is Required")]
        public string StudentName { get; set; }
        public string StudentGender { get; set; }
        public Nullable<int> StudentAge { get; set; }

        [Required(ErrorMessage = "Address is Required")]
        public string StudentAddress { get; set; }

        [Required(ErrorMessage = "Mobile No is Required")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Aadhar No is Required")]
        [StringLength(12, MinimumLength = 12)]
        public string AadharNo { get; set; }

        [Required(ErrorMessage = "Registration No is Required")]
        [StringLength(20, MinimumLength = 5)]
        public string RegistationNo { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> DueAmount { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string FilePath { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Center Center { get; set; }
    }
}
